// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkrqxslzwxnzcpvtxejk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcnF4c2x6d3huemNwdnR4ZWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzA1MDMsImV4cCI6MjA2ODg0NjUwM30.vuJIE1MZnJMj1T5Wp0vlABPtRiKBaAytIQZjYZq3TfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});